### ISSUE TITLE
SNProcess crashes when trying to delete 'tmp' dir

### ISSUE THREAD

**Issue by huzefaKhalil** [dokastho/snprocess#2]
Because the directory isn't empty. Should be an easy fix.

However, I can't find the HTML doc in the output or tmp directory. It should be created before trying to delete the tmp dir, right?

/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/qc/qc_2.py:234: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  output = output.drop(2, 1)
Traceback (most recent call last):
  File "/home/akil_lab/huzefak/.local/bin/snprocess", line 33, in <module>
    sys.exit(load_entry_point('snprocess==1.0.2', 'console_scripts', 'snprocess')())
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/__main__.py", line 163, in main
    clean()
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/model.py", line 40, in clean
    os.rmdir("tmp")
OSError: [Errno 39] Directory not empty: 'tmp'

**Comment by dokastho** [comment]
This was an easy fix! Just had to change the removal of the tmp folder to allow for it to be nonempty. You couldn't find the html file because that step to remove tmp came before the html creation, so the program crashed beforehand.
