### ISSUE TITLE
Can't find plink!

### ISSUE THREAD

**Issue by huzefaKhalil** [dokastho/snprocess#3]
I'm not sure why this is happening now. It was working fine and there haven't been any changes on the server. This happened after the latest upgrade (1.0.3)

Traceback (most recent call last):
  File "/home/akil_lab/huzefak/.local/bin/snprocess", line 33, in <module>
    sys.exit(load_entry_point('snprocess==1.0.3', 'console_scripts', 'snprocess')())
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/__main__.py", line 159, in main
    markup = QC_1(settings)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/qc/qc_1.py", line 36, in QC_1
    output, data = plink(
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/qc/model.py", line 31, in plink
    output = run_command(cmd)
  File "/home/akil_lab/huzefak/.local/lib/python3.10/site-packages/snprocess/qc/model.py", line 18, in run_command
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './plink'

**Comment by dokastho** [comment]
Ahhh my bad, I had forgotten to revert some code I use to debug on my machine. View changes in qc/model.py if you’re curious.
